In [2]:
import numpy as np

1. What is a Python library? Why ^o we use Python libraries?
Ans:
A Python library is a collection of functions and modules that extend the capabilities of the Python programming language. These libraries are developed to provide specific functionalities to simplify common tasks, such as data manipulation, mathematical operations, web development, machine learning, and more.

We use Python libraries for several reasons:

Efficiency: Python libraries provide pre-written code that allows developers to accomplish tasks without having to reinvent the wheel. This saves time and effort in coding complex functionalities from scratch.

Functionality: Libraries extend the capabilities of Python by providing ready-to-use functions and modules for various tasks. This allows developers to access a wide range of features without having to implement them independently.

Community Support: Python has a large and active community of developers who contribute to the creation and maintenance of libraries. This community support ensures that libraries are continuously updated, improved, and well-documented.

Specialized Tasks: Many Python libraries are designed to address specific domains or industries, such as data science, web development, scientific computing, etc. Using these specialized libraries allows developers to leverage domain-specific tools and techniques effectively.

Interoperability: Python libraries are often designed to work well with other libraries and tools, promoting interoperability and allowing developers to combine different functionalities seamlessly.

2. What is the Difference between Numpy array an^ List?
Ans:
NumPy arrays and Python lists are both used to store collections of elements, but they have several differences in terms of functionality, performance, and usage:

Data Types: NumPy arrays are homogeneous, meaning that all elements in the array must have the same data type. This allows for more efficient storage and operations on the array. Python lists, on the other hand, can contain elements of different data types.

Performance: NumPy arrays are more efficient for numerical computations compared to Python lists. NumPy arrays are implemented in C and optimized for performance, whereas Python lists are implemented in Python itself, which can be slower for numerical computations, especially for large datasets.

Memory Usage: NumPy arrays generally consume less memory compared to Python lists, especially for large datasets, because they store data in a contiguous block of memory. Python lists, on the other hand, store references to objects, which can consume more memory.

Functionality: NumPy arrays provide a wide range of mathematical functions and operations for array manipulation, such as element-wise operations, linear algebra, Fourier transforms, statistical functions, etc. Python lists have fewer built-in functions for numerical computations and array manipulation.

Ease of Use: Python lists are more versatile and easier to work with for general-purpose tasks due to their flexibility and dynamic nature. NumPy arrays are more specialized for numerical computations and may require more effort to work with for tasks outside this domain.

In [3]:
#3. Fin^ the shape, size an^ ^imension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
arr1.shape

(3, 4)

In [5]:
arr1.size

12

In [6]:
arr1.ndim

2

In [7]:
# 4. Write python co^e to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr2[0]

array([1, 2, 3, 4])

In [9]:
# 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr3[2,3]

12

In [18]:
# 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr4[arr4%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [24]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
arr5=np.random.rand(3,3)
arr5

array([[0.95447663, 0.38332299, 0.63845375],
       [0.47470983, 0.20003164, 0.34230449],
       [0.40136391, 0.51322265, 0.86404311]])

8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
ANs:

In NumPy, there is a distinction between np.random.rand and np.random.randn. Both functions are used to generate random numbers, but they have different distributions.

1. np.random.rand:

-This function generates random numbers from a uniform distribution over the interval [0, 1)
-The syntax is np.random.rand(d0, d1, ..., dn), where d0, d1, ..., dn are the dimensions of the output array.
-Each value in the output array is sampled independently and uniformly from the range [0, 1).

Example:
# Generate a 1D array of 5 random numbers between 0 and 
random_array = np.random.rand(5)

----------------------------------------------------
2.np.random.randn:

This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
The syntax is np.random.randn(d0, d1, ..., dn), where d0, d1, ..., dn are the dimensions of the output array.
The values in the output array are drawn from a Gaussian distribution with mean 0 and standard deviation 1.
Example:

# Generate a 1D array of 5 random numbers from a standard normal distribution
random_array = np.random.randn(5)


In [25]:
# 9. Write co^e to increase the ^imension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr5=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
arr5.ndim

2

In [27]:
arr5.size

12

In [29]:
arr6=arr5.reshape(1,3,4)

In [30]:
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [31]:
arr6.ndim

3

In [32]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr7.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [68]:
# 11. Consi^er the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# ,+ I(dex wiLe multiplicatio'
# ]+ Matix multiplicatio'
# + Add both the maticK
# -+ Subtact matix B om
A=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
A

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [69]:
B

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [76]:
# index_multiplication
a=np.array(A)
b=np.array(B)
multiply_index=np.multiply(a,b)
multiply_index

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [70]:
multiplication=np.dot(A,B.T)
multiplication

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [72]:
Add=A+B
Add

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [73]:
Subtract=B-A
Subtract

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [74]:
Divide=B/A
Divide

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

12.  Which function in Numpy can be use^ to swap the byte or^er of an array?
Ans:
In NumPy, the byteswap() function can be used to swap the byte order (endianness) of an array. This function swaps the byte order of the elements in the array in-place.

Example:

In [77]:
arr = np.array([1, 256], dtype=np.int16)  # Example array with two elements: 1 and 256
arr_swapped = arr.byteswap()
print("Original array:", arr)
print("Array with byte order swapped:", arr_swapped)


Original array: [  1 256]
Array with byte order swapped: [256   1]


13.  What is the significance of the np.linalg.inv function?
Ans:The `np.linalg.inv()` function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in various mathematical and computational applications, particularly in linear algebra and solving systems of linear equations.

Here are some key points about the significance of `np.linalg.inv()`:

1. Solving Linear Systems**: One of the primary uses of matrix inversion is in solving systems of linear equations. Given a system of equations represented by the matrix equation Ax = b, where A is a square matrix of coefficients, x is the vector of unknowns, and b is the constant vector, you can solve for x by computing the inverse of A: x = A⁻¹b. This is particularly useful when you need to solve systems of equations with multiple variables.

2. Computing Determinants**: The inverse of a matrix A can also be used to compute the determinant of A. Specifically, the determinant of A is equal to 1/det(A⁻¹). This relationship is often exploited in various numerical algorithms and theoretical calculations.

3. Computational Efficiency**: While computing the inverse of a matrix using traditional methods can be computationally expensive, NumPy's `np.linalg.inv()` function is optimized for performance. It uses efficient algorithms, such as LU decomposition, to compute the inverse of the matrix quickly and accurately.

4. Applications in Statistics and Optimization**: Matrix inversion is a fundamental operation in various fields such as statistics, optimization, and machine learning. It is used in techniques like linear regression, least squares estimation, and parameter estimation in probabilistic models.

5. Checking Singularity**: The `np.linalg.inv()` function can also be used to check if a matrix is singular (i.e., non-invertible). If the determinant of the matrix is zero, it implies that the matrix is singular, and its inverse does not exist.

14. What ^oes the np.reshape function ^o, an^ how is it use^?
Ans:
The np.reshape() function in NumPy is used to change the shape (dimensions) of an array without changing its data. It allows you to rearrange the elements of an array into a new shape while preserving the total number of elements.

It's important to note that the total number of elements in the reshaped array must be equal to the total number of elements in the original array. Otherwise, np.reshape() will raise a ValueError. Additionally, reshaping doesn't change the underlying data; it only changes the way the data is interpreted based on the new shape.

Example:

In [79]:
arr = np.arange(9)
reshaped_arr = np.reshape(arr, (3, 3))
print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)


Original array:
[0 1 2 3 4 5 6 7 8]

Reshaped array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


15. What is broa^casting in Numpy?
Ans:
Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined in arithmetic operations. It enables you to perform element-wise operations between arrays of different shapes without explicitly reshaping or duplicating the smaller array to match the shape of the larger array.

The basic concept of broadcasting can be summarized as follows:

1. Shape Compatibility**: Broadcasting begins when NumPy tries to perform an operation on arrays with different shapes. NumPy compares their shapes element-wise, starting from the trailing dimensions (i.e., the rightmost dimensions) and working backward. Two dimensions are considered compatible when:
   - They are equal, or
   - One of them is 1.

2. Broadcasting Rule**: Once NumPy identifies compatible dimensions, it automatically "broadcasts" the smaller array to match the shape of the larger array by replicating its elements along the dimensions where its size is 1.

3. Element-Wise Operation**: After broadcasting, NumPy performs the element-wise operation between the two arrays as if they were the same shape.

Broadcasting simplifies array operations, making code more concise and readable, and often eliminates the need for explicit loops or reshaping operations. However, it's essential to understand how broadcasting works to avoid unexpected results or errors in your code.

In [80]:
arr1 = np.array([1, 2, 3])         # shape: (3,)
arr2 = np.array([[10], [20], [30]]) # shape: (3, 1)
result = arr1 + arr2
print(result)


[[11 12 13]
 [21 22 23]
 [31 32 33]]
